version: '2.1'

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: $NPM_TOKEN
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE=postgres
      - LOGLEVEL=crit
      - NODE_ENV=test
      - POSTGRES_DATABASE=jellyfish
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - REDIS_HOST=redis
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - OAUTH_REDIRECT_BASE_URL=https://jel.ly.fish
      - INTEGRATION_DEFAULT_USER=admin
      - TEST_INTEGRATION_DISCOURSE_CATEGORY=44
      - TEST_INTEGRATION_DISCOURSE_USERNAME=jellyfish
      - TEST_INTEGRATION_DISCOURSE_NON_MODERATOR_USERNAME=jellyfish-test
      - INTEGRATION_DISCOURSE_SIGNATURE_KEY
      - INTEGRATION_DISCOURSE_TOKEN
      - INTEGRATION_DISCOURSE_USERNAME
      - CI=1
      - NPM_TOKEN
    networks:
      - internal
