version: '2.1'

services:
  sut:
    image: balena/jellyfish-sut:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    secrets:
      - integration_discourse_signature_key
      - integration_discourse_token
      - integration_discourse_username
    networks:
      - internal

secrets:
  integration_discourse_signature_key:
    file: ./.balena/secrets/integration_discourse_signature_key
  integration_discourse_token:
    file: ./.balena/secrets/integration_discourse_token
  integration_discourse_username:
    file: ./.balena/secrets/integration_discourse_username
