version: '3'

env:
  INTEGRATION_DISCOURSE_SIGNATURE_KEY:
    sh: cat /run/secrets/integration_discourse_signature_key
  INTEGRATION_DISCOURSE_TOKEN:
    sh: cat /run/secrets/integration_discourse_token
  INTEGRATION_DISCOURSE_USERNAME:
    sh: cat /run/secrets/integration_discourse_username

tasks:
  test:
    cmds:
      - npm run test:integration
