version: '3'

env:
  INTEGRATION_DISCOURSE_TOKEN:
    sh: cat /run/secrets/integration_discourse_token
  INTEGRATION_DISCOURSE_USERNAME:
    sh: cat /run/secrets/integration_discourse_username

tasks:
  test:
    cmds:
      - npm run test:integration
      - cmd: npm run delete-test-data
        ignore_error: true
